### ISSUE TITLE
Add support for ElasticSearch

### ISSUE THREAD

**Issue by juniorplenty** [evolvingweb/ajax-solr#27]
This has been mentioned in other threads, adding here as an official feature request. Elasticsearch is rapidly replacing Solr in a lot of organizations, and in general is a more modern, abstracted wrapper than Solr. I have used and love ajax-solr, would love to keep using it now that we've migrated to Elasticsearch, and I'm sure others feel the same.

Anyway - here for comment

**Comment by jpmckinney** [comment]
Still a good idea, but development on ajax-solr has been fairly static for a while now, so closing until someone starts a pull request.
