### ISSUE TITLE
Add AjaxSolr.ParameterYUI3Store using YUI 3.9.0

### ISSUE THREAD

**Issue by lewismc** [evolvingweb/ajax-solr#28]
Hi JP,
I am working on upgrading the small API usage we have here but coming across some small problems which I need to look into.
I've forked the code and will send a pull once I get it working.
For reference, new library
http://yui.yahooapis.com/3.9.0/build/yui/yui-min.js

**Comment by lewismc** [comment]
hey @jpmckinney apologies for not getting around to this. WOW how time flies!

**Comment by jpmckinney** [comment]
No worries! Just cleaning older issues across my repos.
