### ISSUE TITLE
Capturing Errors

### ISSUE THREAD

**Issue by JSnoob** [evolvingweb/ajax-solr#31]
If a search entry produces an error in Solr: ie 

<pre><code>
&lt; lst name="error" &gt;
  &lt; str name="msg" &gt; org.apache.solr.earch.SyntaxError: undefined field / &gt; &lt; str /&gt;
  &lt; int name="code" &gt; 400  &lt; / &gt;
&lt; /lst &gt;

</code></pre>

How can we get modify ajax-solr to have this error message returned? Currently, there is no data in the Manager.response object when an error occurs.

**Comment by dannyrose42** [comment]
I have question. The "message" passed to the handleError method seems to be _the ajax call error _mesage__ (which is often the unhelpful "error").  Is there away to get to the actual error message of the Solr Response?

**Comment by jpmckinney** [comment]
I usually have my browser's network inspector open so that I can see what request was sent to Solr. I then copy that request and send it myself to see the original error message.

**Comment by dannyrose42** [comment]
Thanks for the response. Thanks actually exactly what I ended up doing. I'm guessing the responseHeaders are blank because of something to do with same-origin policy? Great work on this plugin by the way, I've been loving it.

**Comment by jpmckinney** [comment]
I'm not exactly sure - a few things can cause the error message to be less helpful.
