### ISSUE TITLE
Demo Site Not Working

### ISSUE THREAD

**Issue by dannyrose42** [evolvingweb/ajax-solr#60]
This is an awesome resource but sadly I think there my be something wrong with demo site. It just shows the loading animation forever for me. 
![2016-01-20 08_17_22-ajax solr](https://cloud.githubusercontent.com/assets/5464924/12451341/64c1e5fe-bf4e-11e5-87ff-3f4518a1257e.png)

**Comment by dergachev** [comment]
Yep tomcat is down, I'll take a look!

On Wednesday, 20 January 2016, Danny Rose <notifications@github.com> wrote:

> This is an awesome resource but sadly I think there my be something wrong
> with demo site. It just shows the loading animation forever for me.
> [image: 2016-01-20 08_17_22-ajax solr]
> <https://cloud.githubusercontent.com/assets/5464924/12451341/64c1e5fe-bf4e-11e5-87ff-3f4518a1257e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evolvingweb/ajax-solr/issues/60>.
>


-- 
------------------------------------------------------------------------------------
Alex Dergachev            Evolving Web
Lead developer            web design & development
alex@evolvingweb.ca        http://evolvingweb.ca
phone 514.844.4930        300 St Sacrement, #204
fax 514.807.7499        Montreal, QC, H2Y 1X4
------------------------------------------------------------------------------------

**Comment by dannyrose42** [comment]
You da best.

**Comment by dergachev** [comment]
Restarted solr, all good for now

**Comment by dannyrose42** [comment]
Awesome. Thanks so much!

**Comment by casertap** [comment]
It is down, once again.
I would love to see it running. I am interested in this plugin

**Comment by dergachev** [comment]
FYI working
